### ISSUE TITLE
xsl:result-document

### ISSUE THREAD

**Issue by mhbeals** [russlescai/atom-xsltransform#4]
This processor does not handle the 2.0 command xsl:result-document. Can this be included?

**Comment by russlescai** [comment]
I am using the native JavaScript XSLTProcessor, so I don't have a lot of control over which XSL commands are supported.

I could, however, include an option to make the xsl engine configurable. That would also fix #5 since you could use saxon or another processor to convert to MD.

**Comment by mhbeals** [comment]
That would be very useful. Thank you.

**Comment by nicolaiax** [comment]
+1 from me on that too :)

Thanks for all your work on this @russlescai

**Comment by russlescai** [comment]
With the latest version, you can specify the XSLT tool to use (which supports xslt v2) instead of using the native.

I have updated the README with some examples, let me know if you have any issues! :)
