### ISSUE TITLE
Fails with space on pathnames

### ISSUE THREAD

**Issue by eduardot42** [russlescai/atom-xsltransform#7]
Does not work with files where the full pathname has a space, e.g. Google Drive. Running on Mac OS X Yosemite.

Attached is a screenshot:

![image](https://cloud.githubusercontent.com/assets/8451602/9152177/e866dfca-3deb-11e5-86f0-3ac6a87273bf.png)

**Comment by nicolaiax** [comment]
When you define your engine and path put your xml and xsl in quotes, I.e xml="%xml".

Rgds Nico

**Comment by eduardot42** [comment]
Got it, thanks for the info. I just copy + pasted from the sample, I’d suggest putting quotes around it there. Also some cool functionality would be to add ability to use an open tab as the source XSLT. More suggestions would be keystroke shortcuts to get a menu just for this tool, or to do actions for this tool.

If you need help I can dab into atom plugin development and help you out.

**Comment by russlescai** [comment]
thanks for the post @eduardot42, I'll add quotes around filenames inside the package so you don't have to worry about it.

As @nocolaoiax said, if you are using a custom xsl tool you can add quotes until I get it published.

I'll try to get to it today or tomorrow (Australia time :) ).

**Comment by russlescai** [comment]
Thanks for the idea @eduardot42. :) I'll have a think how best to do the xsl in a tab also.

**Comment by nicolaiax** [comment]
Cool :) I'm trying to develop a autocomplete+ package for xsl completion. 

Other things needed for xml is xpath/xquery "resolver" to get xpath from xml file and to run it (or any xpath ) against your xml file and see the results of it 

Rgds Nico

**Comment by nicolaiax** [comment]
How about a right click menu to apply stylesheet when you are in the xml?

**Comment by eduardot42** [comment]
Oh, I have a bunch of snippets from my work. I was using Sublime Text 2 but decided to try atom. Loving it already, so transforming all my Sublime Snippets into atom snippets. I can send you the source I create once it's all done.

**Comment by eduardot42** [comment]
I'm not a big fan of right click, I prefer keyboard shortcuts that pop up a menu. But the same backend logic can be used for both right click and keyboard, so once one is done both become available.

Eduardo Toledo

**Comment by russlescai** [comment]
I have published a new version which fixes the file paths with spaces issue. You do not need quotes in the settings now.

I am still trying to work out the most intuitive behaviour for opening current XSL and XML documents.
