### ISSUE TITLE
No transform, no obvious error on two machines

### ISSUE THREAD

**Issue by fburleigh** [russlescai/atom-xsltransform#8]
I was happy to find this package -- it is a great solution to a problem that's just appeared in my inbox.  But on two machines -- my Mac and a Windows 7 machine with a fresh Atom install -- the result is a 3 line document with no other content. There are no errors on the console.

I've tested with a publishing workflow I use regularly with xsltproc and with the test.xml and test.xsl samples.

I don't have development experience in Atom or its packages; if there's a knob I can twiddle to produce some debug info, do let me know.

PS: line 11 of text.xsl includes a call to `xsl:value-of2`.

**Comment by russlescai** [comment]
Have you setup the xsltproc command line in package settings? (Open settings, find the XSLT Transform package, click Settings).

Set the xsltproc command to:
xsltproc %XSL %XML

Hope that helps :)

**Comment by fburleigh** [comment]
No, I hadn't -- because I'd hoped to rely on the default behavior:

> By default, this package uses JavaScript native XSLTProcessor, without any OS dependent tools.

to support my users on Windows where there is Atom but no inherent platform support for XSL.

Thanks for the hint though -- the customized command does provide a workaround on OS X.

**Comment by nicolaiax** [comment]
@fburleigh:
I changed xslt processor to use saxon which is an open source java library. It should work on all OS where Java is supported.

Here's the link to the saxon XSLT and XQuery processor (open-source) from
http://sourceforge.net/projects/saxon/?source=typ_redirect. I then
extracted the zip file once downloaded and added it to my Java Library
Extensions folder (OSX = open your HD -> Library -> Java -> Extensions,
added saxon9he.jar & saxon9-xqj.jar).

I opened the xmltransform package settings in Atom (open config folder ->
packages -> atom-xmltransform -> lib -> atom-xmltransform.coffee), this is
the config part of the file where I changed the default "path":
config:
externalXslToolPath:
type: 'string'
default: 'java net.sf.saxon.Transform -s:"%XML" -xsl:"%XSL"'
description: 'The path to an external Xsl tool. Use %XSL and %XML for file
parameters'

**Comment by CircuitMusicLabs** [comment]
I just dropped in here to confirm that on my clean installation of atom, the package produces a three-line empty document. I cannot install external resources and depend on the default behaviour, which behaves the same way as fburleigh describes in the first post.

Any help would be appreciated.

**Comment by nicolaiax** [comment]
Russ, I thought, due to file names that you wanted it in quotes like this:
xsltproc "%XSL" "%XML"

**Comment by nicolaiax** [comment]
Also check the closed post here
https://github.com/russlescai/atom-xsltransform/issues/5. It has step by
step instructions to download a Saxon package for the transformation (needs
to be placed with you Java Runtime), call it by

saxon -s:"%XML" -xsl:"%XSL"

**Comment by uschaefer** [comment]
I can confirm the issue for Atom 1.5.3 on Windows and the latest xsl transform plugin. I'd like to use the internal XSLT engine instead of an external program, but only get 3 empty lines as output buffer.
Having the possibility to specify an output format (xml|text|html) would be a good idea.

**Comment by ColinEberhardt** [comment]
Just to add 'me too' to the list - I get the same 3-line output

**Comment by netsi1964** [comment]
I had same issues on windows. Here is what I did:
-  Download, extract and copy msxsl.exe (https://www.microsoft.com/en-us/download/details.aspx?id=21714) to say root of "C:"
-  Change the setting "External Xsl Tool Path" in the Atom Xsltransform package to: "`\msxsl.exe  %XML %XSL`"

Now it should be possible to do XSLT transformation by
-  Have the XML open
-  opening the command window (Shift-Ctrl-P) and enter "`Atom Xsltransform`". Press `enter`
-  Enter the path to the XSLT stylesheet you want to use

**Comment by reuwi** [comment]
I came across this same problem, and when  I tried to config the settings of this package, I found that this package didn't have the setting option, so what should I do.....

**Comment by russlescai** [comment]
@gaoshijun1993 the next version (hopefully build today) will include the default behaviour if no xslt processor is specified. There was an issue with the default value being returned from the config.
